### ISSUE TITLE
Can I only run the freq job and only using Qchem as my ESS?

### ISSUE THREAD

**Issue by NtuCheRoy** [ReactionMechanismGenerator/ARC#194]
I want to run a simple job, using Qchem to analyze hydrogen with b3lyp/6-31g* level of theory. I have set up my yml file with below code.
```
job_types:
    freq: true
```
However, the output file shows that ARC turns out to run the opt, conformers, sp, 1d_rotors, freq and fine job together. My first question is that can I only run freq job? Below is the message from output file.
![image](https://user-images.githubusercontent.com/53944308/64925340-96fa0980-d821-11e9-8c27-e8002caa6195.png)
And my server only has Qchem as ESS. I watch the arc/settings.py file, and in the 84 line it show that `level_ess` is the default that level and basis set relating to specific ESS. If I want to use Qchem to analyze some molecules  with b3lyp/6-31g* level of theory. It seems that I have to set up the `level_ess`. Otherwise, it would have `KeyError: 'gaussian'`. I try to set up the `level_ess` by type below code in my yml file, but still have `KeyError: 'gaussian'`. Could you tell me how to run job by only using Qchem as ESS?
```
levels_ess:
    qchem:
    - b3lyp
```

**Comment by alongd** [comment]
To run a single job type, you need to specify all other job types as `False` in under `job_types`:
```yaml
job_types:
    conformers: false
    opt: false
    fine_grid: false
    freq: true
    1d_rotors: false
    sp: false
```

Soon, this will not be necessary (once #186 is merged) and a user will be able to request this behaviour via the `specific_job_type` argument.
Note that if your species is only represented in the input file using SMILES and does not have a 3D xyz geometry, conformers will be spawned, and perhaps opt as well.

Regarding your second question: To direct ARC to use QChem for a certain level of theory, you should modify the `levels_ess` dictionary in the settings.py file, it's not a part of the input file. Use, for example:

```yaml
levels_ess = {
    'gaussian': ['apfd', 'b3lyp', 'm062x'],
    'molpro': ['ccsd', 'cisd', 'vpz'],
    'qchem': ['b3lyp']
}
```

**Comment by NtuCheRoy** [comment]
I type below code in my yml file. However, in my output file it seems that ARC still run not only freq job.
```
project: arc_demo_1

ess_settings:
        qchem:
                - local

job_types:
        conformers: false
        opt: false
        fine: false
        freq: true
        sp: false
        1d_rotors: false
        orbitals: false
        lennard_jones: false
        bde: false

level_of_theory: b3lyp/6-31g*
conformer_level: b3lyp/6-31g*
scan_level: b3lyp/6-31g*
ts_guess_level: b3lyp/6-31g*

species:
  - label: hydrogen
    xyz: |
            H         -4.12347       -0.08887        0.00000
            H         -3.70381        0.48134        0.00000
```
![image](https://user-images.githubusercontent.com/53944308/64940955-f266de80-d897-11e9-831d-03488a7b3ce7.png)

And as for my second question. I have setup `levels_ess`, but get `KeyError: 'local'`. Below figure is the trace message. And I try to modify arc/settings.py line 51~53 in below way, but still get `Keyerror`.
```
    'local': {
        'cluster_soft': 'Slurm',
        'un': '<shcheng>',
    },
```
![image](https://user-images.githubusercontent.com/53944308/64941182-7e790600-d898-11e9-8399-60741ab19783.png)
