### ISSUE TITLE
Cannot compute rates if a reactants/product species is given from an Arkane YAML file

### ISSUE THREAD

**Issue by MichalKesl** [ReactionMechanismGenerator/ARC#518]
**Describe the bug**
We gave the following input:

```yaml
project: xh2010

level_of_theory: cbs-qb3
compute_thermo: false
freq_scale_factor: 1
job_types:
  rotors: false 
species:
  - label: N2H3 #N2H3(14)
    multiplicity: 2
    smiles: N[NH]
    yml_path: /N2H3.yml
  - label: HNNH_S #N2H2(16)
    adjlist: | 
             1 N u0 p1 c0 {2,D} {3,S}
             2 N u0 p1 c0 {1,D} {4,S}
             3 H u0 p0 c0 {1,S}
             4 H u0 p0 c0 {2,S}
  - label: H2NN_S #N2H2(18)
    adjlist: | 
             1 N u0 p0 c+1 {2,D} {3,S} {4,S}
             2 N u0 p2 c-1 {1,D}
             3 H u0 p0 c0 {1,S}
             4 H u0 p0 c0 {1,S}
  - label: NNH_T #NNH(71)
    multiplicity: 2
    adjlist: |
             1 N u0 p1 c0 {2,D} {3,S}
             2 N u1 p1 c0 {1,D}
             3 H u0 p0 c0 {1,S}

reactions:
  - label: N2H3 + NNH_T <=> HNNH_S + HNNH_S
    ts_xyz_guess: 
    - TS5_1.xyz
```

TS5_1.xyz:
```
8
TS5_1 optimized at cbs-qb3
N      -0.68300700    0.03920500   -0.01784800
N       0.59224500    0.17784500   -0.25555500
H      -1.15241800   -0.11589500   -0.91590900
H      -1.11625500    1.05983800    0.37745200
H       1.04909600    0.28531300    0.65574300
N       0.28393500    2.40293300   -0.02808700
N      -0.86072400    2.47720000    0.28870900
H       0.81945200    3.28758400   -0.10802200
```

N2H3.yml:
```yaml
RMG_version: 3.1.0
adjacency_list: |
  multiplicity 2
  1 N u0 p1 c0 {2,S} {3,S} {4,S}
  2 N u1 p1 c0 {1,S} {5,S}
  3 H u0 p0 c0 {1,S}
  4 H u0 p0 c0 {1,S}
  5 H u0 p0 c0 {2,S}
charge: 0
chemkin_thermo_string: |
  N2H3                    H   3N   2          G    10.000  3000.000  350.19      1
   2.24346053E+00 1.16909712E-02-6.10437318E-06 1.62082407E-09-1.71821013E-13    2
   2.45063257E+04 1.32073021E+01 4.04686435E+00-4.17784458E-03 4.16057334E-05    3
  -5.06318502E-08 9.59258103E-12 2.43510147E+04 5.98507052E+00                   4
class: ArkaneSpecies
conformer:
  E0:
    class: ScalarQuantity
    units: kJ/mol
    value: 202.4587661272151
  class: Conformer
  coordinates:
    class: ArrayQuantity
    units: angstroms
    value:
      class: np_array
      object:
      - - -0.423202
        - 0.0031879999999999994
        - 0.17559
      - - 0.791998
        - -0.531317
        - -0.089405
      - - -1.18531
        - -0.643555
        - 0.030107
      - - -0.637947
        - 0.959795
        - -0.089111
      - - 1.43929
        - 0.262891
        - -0.107737
  mass:
    class: ArrayQuantity
    units: amu
    value:
      class: np_array
      object:
      - 14.00307400443
      - 14.00307400443
      - 1.00782503224
      - 1.00782503224
      - 1.00782503224
  modes:
  - class: IdealGasTranslation
    mass:
      class: ScalarQuantity
      units: amu
      value: 31.029620000000005
    quantum: false
  - class: NonlinearRotor
    inertia:
      class: ArrayQuantity
      units: amu*angstrom^2
      value:
        class: np_array
        object:
        - 2.4805399332066242
        - 16.541888316394743
        - 18.72298334799242
    quantum: false
    rotationalConstant:
      class: ArrayQuantity
      units: cm^-1
      value:
        class: np_array
        object:
        - 6.79595148930194
        - 1.0190873454659235
        - 0.9003708832094891
    symmetry: 1
  - class: HarmonicOscillator
    frequencies:
      class: ArrayQuantity
      units: cm^-1
      value:
        class: np_array
        object:
        - 580.190604816537
        - 714.8648764077677
        - 1146.2104788486065
        - 1239.4121636437396
        - 1495.3923561698548
        - 1675.5999557273262
        - 3410.610927028133
        - 3480.194727182487
        - 3633.6656254272652
    quantum: true
  number:
    class: ArrayQuantity
    value:
      class: np_array
      object:
      - 7.0
      - 7.0
      - 1.0
      - 1.0
      - 1.0
  optical_isomers: 2
  spin_multiplicity: 2
datetime: 2022-05-30 17:39
formula: H3N2
inchi: InChI=1S/H3N2/c1-2/h1H,2H2
inchi_key: LURQBQNWDYASPJ-UHFFFAOYSA-N
is_ts: false
label: N2H3
molecular_weight:
  class: ScalarQuantity
  units: amu
  value: 31.03763485763127
multiplicity: 2
smiles: '[NH]N'
thermo:
  Cp0:
    class: ScalarQuantity
    units: J/(mol*K)
    value: 33.257888
  CpInf:
    class: ScalarQuantity
    units: J/(mol*K)
    value: 108.08813599999999
  E0:
    class: ScalarQuantity
    units: kJ/mol
    value: 202.46339830137327
  Tmax:
    class: ScalarQuantity
    units: K
    value: 3000.0
  Tmin:
    class: ScalarQuantity
    units: K
    value: 10.0
  class: NASA
  polynomials:
    polynomial1:
      Tmax:
        class: ScalarQuantity
        units: K
        value: 350.18692551807146
      Tmin:
        class: ScalarQuantity
        units: K
        value: 10.0
      class: NASAPolynomial
      coeffs:
        class: np_array
        object:
        - 4.046864353249508
        - -0.004177844580689019
        - 4.1605733369059456e-05
        - -5.063185015261333e-08
        - 9.592581033254738e-12
        - 24351.014666958064
        - 5.98507052402682
    polynomial2:
      Tmax:
        class: ScalarQuantity
        units: K
        value: 3000.0
      Tmin:
        class: ScalarQuantity
        units: K
        value: 350.18692551807146
      class: NASAPolynomial
      coeffs:
        class: np_array
        object:
        - 2.2434605251957467
        - 0.011690971222545773
        - -6.1043731811830374e-06
        - 1.6208240695555914e-09
        - -1.718210126371354e-13
        - 24506.325699213452
        - 13.207302056500666
thermo_data:
  Cpdata:
    class: ArrayQuantity
    units: cal/(mol*K)
    value:
      class: np_array
      object:
      - 10.430185053605145
      - 12.007662349549431
      - 13.423017607205214
      - 14.682075623534569
      - 16.78975412368534
      - 18.43941158094492
      - 21.154836732516408
      - 22.704562782939714
      - 23.54097490819626
  H298:
    class: ScalarQuantity
    units: kcal/mol
    value: 50.958282136896564
  S298:
    class: ScalarQuantity
    units: cal/(mol*K)
    value: 58.056424230772535
  Tdata:
    class: ArrayQuantity
    units: K
    value:
      class: np_array
      object:
      - 300.0
      - 400.0
      - 500.0
      - 600.0
      - 800.0
      - 1000.0
      - 1500.0
      - 2000.0
      - 2400.0
  class: ThermoData
xyz: |-
  5
  N2H3
  N      -0.42320200    0.00318800    0.17559000
  N       0.79199800   -0.53131700   -0.08940500
  H      -1.18531000   -0.64355500    0.03010700
  H      -0.63794700    0.95979500   -0.08911100
  H       1.43929000    0.26289100   -0.10773700
```

ARC did not compute any rate since it didn't get E0 for the N2H3 species tread from YAML:

```
Reaction N2H3 + NNH_T <=> HNNH_S + HNNH_S (TS TS0) has the following path electronic energy:
Reactants: None
TS: 64.83 kJ/mol
Products: 0.00 kJ/mol
```
