### ISSUE TITLE
Specifying both SMILES and xyz for HNO2 results in a wrong Molecule

### ISSUE THREAD

**Issue by alongd** [ReactionMechanismGenerator/ARC#531]
Running a species defined as:

```yaml
species:
  - label: HNO2
    smiles: '[O-][NH+]=O'
    multiplicity: 1
    xyz: |
      O      -1.01386486   -0.68945953    0.00479924
      N      -0.00259331    0.01680748    0.00034704
      O       1.17442937   -0.35117532   -0.02628640
      H      -0.15797121    1.02382738    0.02114012
```

results in a wrong Molecule object representation:
```
Considering species: HNO2
<Molecule "[O]N[O]">
```

with invalid adj list:
```
1 O u0 p2 c0 {3,S}
2 O u0 p2 c0 {3,S}
3 N u0 p1 c0 {1,S} {2,S} {4,S}
4 H u0 p0 c0 {3,S}
```

This causes ARC to identify H_Abstraction reactions from HNO2 as Disprop.

The bypass for now is to not use the xyz when defining the species, but the perception issue should be looked at.
