### ISSUE TITLE
ConverterError in a species from the RMGDB

### ISSUE THREAD

**Issue by kfir4444** [ReactionMechanismGenerator/ARC#639]
**Describe the bug**
while  performing 1D scans on a list of species from the RMGDB, I encountered an error:
```python
Traceback (most recent call last):
  File f"{arc_path}/ARC.py", line 69, in <module>
    main()
  File f"{arc_path}/ARC.py", line 65, in main
    arc_object.execute()
  File f"{arc_path}/arc/main.py", line 583, in execute
    fine_only=self.fine_only,
  File f"{arc_path}/arc/scheduler.py", line 484, in __init__
    self.schedule_jobs()
  File f"{arc_path}/arc/scheduler.py", line 500, in schedule_jobs
    self.run_conformer_jobs()
  File f"{arc_path}/arc/scheduler.py", line 1030, in run_conformer_jobs
    self.process_conformers(label)
  File f"{arc_path}/arc/scheduler.py", line 1736, in process_conformers
    is_ts=False,
  File f"{arc_path}/arc/plotter.py", line 935, in save_conformers_file
    b_mol = molecules_from_xyz(xyz, multiplicity=multiplicity, charge=charge)[1]
  File f"{arc_path}/arc/species/converter.py", line 1417, in molecules_from_xyz
    set_multiplicity(mol_s1_updated, mol_bo.multiplicity, charge, radical_map=mol_bo)
  File f"{arc_path}//arc/species/converter.py", line 1451, in set_multiplicity
    set_radicals_by_map(mol, radical_map)
  File f"{arc_path}/arc/species/converter.py", line 1566, in set_radicals_by_map
    '{0} is not {1}.'.format(atom.element.symbol, radical_map.atoms[i].symbol))
arc.exceptions.ConverterError: Atom order in mol and radical_map in set_radicals_by_map() do not match. O is not C.
```

**How to reproduce**
```yml
allow_nonisomorphic_2d: true
compute_thermo: false
job_types:
  bde: false
  conformers: false
  fine: false
  freq: false
  opt: true
  rotors: true
  sp: true
level_of_theory: wb97xd/def2tzvp
project: 1d
species:
- directed_rotors: &id001
    cont_opt:
    - all
  label: '796'
  smiles: '[O]OS(O)(C)C'
trsh_ess_jobs: false
```
