### ISSUE TITLE
Using bruteforce torsional scans blocks up servers storange and queue

### ISSUE THREAD

**Issue by kfir4444** [ReactionMechanismGenerator/ARC#660]
**Describe the bug**
When running directed rotor jobs with the brute force (opt & sp) keywords, arc submits all jobs at once, and not checking convergence. This leads to issues with the queue getting over-filled, (which leads to jobs not running, and in general impolite towards other users), and (since jobs are not checked and deleted), the files generated by one job is enough to reach disk quota.

**How to reproduce**
Run jobs with any lot and with species with > 1 torsions:
```yml
species:
  - label: your spc
    smiles: your spc
    directed_rotors:
        brute_force_sp:
        - - all
```

**Expected behavior**
Either define how many jobs can run simultaneously, or run them one by one.1
